//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFerreteria.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoDeSeguridad
    {
        public string Talle { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Peso { get; set; }
        public string TipoEquipo { get; set; }
        public string Normativa { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
