//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFerreteria.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementoDeSujecion
    {
        public string TipoElemento { get; set; }
        public string Codigo { get; set; }
        public Nullable<double> Longitud { get; set; }
        public Nullable<double> Capacidad { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
