//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFerreteria.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HerramientaElectrica
    {
        public string Potencia { get; set; }
        public string Modelo { get; set; }
        public string Codigo { get; set; }
    
        public virtual Herramienta Herramienta { get; set; }
    }
}
