//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFerreteria.CDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Herramienta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Herramienta()
        {
            this.HerramientaElectricas = new HashSet<HerramientaElectrica>();
            this.HerramientaManuals = new HashSet<HerramientaManual>();
        }
    
        public string Modelo { get; set; }
        public string Codigo { get; set; }
    
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HerramientaElectrica> HerramientaElectricas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HerramientaManual> HerramientaManuals { get; set; }
    }
}
